[project]
name = "synthethic-ml-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.6.0",
    "python-dotenv>=1.1.0",
    "sarvamai>=0.1.5",
    "tqdm>=4.67.1",
]
